[mgr]
append_keymap = [
	{ on = "<c-t>",         run = "shell --block zsh",         desc = "Run a shell command" },
]
# diff tool
[[mgr.prepend_keymap]]
on = ["\\","d"]
run = ["shell 'delta \"$1\" \"$0\" | less' --block"]
desc = "Diff the selected with the hovered file"

[[mgr.prepend_keymap]]
on = ["\\","D"]
run = ["shell 'nvim -d \"$1\" \"$0\"' --block"]
desc = "Diff the selected with the hovered file"

# plugin keymap
[[mgr.prepend_keymap]]
on = "<C-y>"
run = ["plugin system-clipboard"]

[[mgr.prepend_keymap]]
on = "<C-v>"
run = ["shell 'cpaste' --block"]

[[mgr.prepend_keymap]]
on   = [ "c", "a", "a" ]
run  = "plugin compress"
desc = "Archive selected files"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "p" ]
run  = "plugin compress -p"
desc = "Archive selected files (password)"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "h" ]
run  = "plugin compress -ph"
desc = "Archive selected files (password+header)"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "l" ]
run  = "plugin compress -l"
desc = "Archive selected files (compression level)"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "u" ]
run  = "plugin compress -phl"
desc = "Archive selected files (password+header+level)"

[[mgr.prepend_keymap]]
on = [ "m" ]
run = "plugin bookmarks 'save'"
desc = "Save current position as a bookmark"

[[mgr.prepend_keymap]]
on = [ "'" ]
run = "plugin bookmarks 'jump'"
desc = "Jump to a bookmark"

[[mgr.prepend_keymap]]
on = [ "b", "d" ]
run = "plugin bookmarks 'delete'"
desc = "Delete a bookmark"

[[mgr.prepend_keymap]]
on = [ "b", "D" ]
run = "plugin bookmarks 'delete_all'"
desc = "Delete all bookmarks"

 
